//!
//! Wrapping for OpenSSL Crypto Backend Implementation for XmlSec Crypto Interface
//!
use crate::bindings;


/// Supported digesting and signing methods as specified by the XML standard.
#[allow(missing_docs)]
pub enum XmlSecSignatureMethod {
    #[cfg(has_aes128_cbc)]       Aes128Cbc,
    #[cfg(has_aes128_gcm)]       Aes128Gcm,
    #[cfg(has_aes192_cbc)]       Aes192Cbc,
    #[cfg(has_aes192_gcm)]       Aes192Gcm,
    #[cfg(has_aes256_cbc)]       Aes256Cbc,
    #[cfg(has_aes256_gcm)]       Aes256Gcm,
    #[cfg(has_concatkdf)]        ConcatKdf,
    #[cfg(has_des3_cbc)]         Des3Cbc,
    #[cfg(has_dhes)]             DhEs,
    #[cfg(has_dsa_sha1)]         DsaSha1,
    #[cfg(has_dsa_sha256)]       DsaSha256,
    #[cfg(has_ecdh)]             Ecdh,
    #[cfg(has_ecdsa_ripemd160)]  EcdsaRipemd160,
    #[cfg(has_ecdsa_sha1)]       EcdsaSha1,
    #[cfg(has_ecdsa_sha224)]     EcdsaSha224,
    #[cfg(has_ecdsa_sha256)]     EcdsaSha256,
    #[cfg(has_ecdsa_sha3_224)]   EcdsaSha3_224,
    #[cfg(has_ecdsa_sha3_256)]   EcdsaSha3_256,
    #[cfg(has_ecdsa_sha3_384)]   EcdsaSha3_384,
    #[cfg(has_ecdsa_sha3_512)]   EcdsaSha3_512,
    #[cfg(has_ecdsa_sha384)]     EcdsaSha384,
    #[cfg(has_ecdsa_sha512)]     EcdsaSha512,
    #[cfg(has_gost2001)]         Gost2001,
    #[cfg(has_gost2012_256)]     Gost2012_256,
    #[cfg(has_gost2012_512)]     Gost2012_512,
    #[cfg(has_gost94)]           Gost94,
    #[cfg(has_hmac_md5)]         HmacMd5,
    #[cfg(has_hmac_ripemd160)]   HmacRipemd160,
    #[cfg(has_hmac_sha1)]        HmacSha1,
    #[cfg(has_hmac_sha224)]      HmacSha224,
    #[cfg(has_hmac_sha256)]      HmacSha256,
    #[cfg(has_hmac_sha384)]      HmacSha384,
    #[cfg(has_hmac_sha512)]      HmacSha512,
    #[cfg(has_kw_aes128)]        KWAes128,
    #[cfg(has_kw_aes192)]        KWAes192,
    #[cfg(has_kw_aes256)]        KWAes256,
    #[cfg(has_kw_des3)]          KWDes3,
    #[cfg(has_md5)]              Md5,
    #[cfg(has_pbkdf2)]           Pbkdf2,
    #[cfg(has_ripemd160)]        Ripemd160,
    #[cfg(has_rsa_md5)]          RsaMd5,
    #[cfg(has_rsaoaep_enc11)]    RsaOaepEnc11,
    #[cfg(has_rsa_oaep)]         RsaOaep,
    #[cfg(has_rsa_pkcs1)]        RsaPkcs1,
    #[cfg(has_rsapsssha1)]       RsaPssSha1,
    #[cfg(has_rsapsssha224)]     RsaPssSha224,
    #[cfg(has_rsapsssha256)]     RsaPssSha256,
    #[cfg(has_rsapsssha3_224)]   RsaPssSha3_224,
    #[cfg(has_rsapsssha3_256)]   RsaPssSha3_256,
    #[cfg(has_rsapsssha3_384)]   RsaPssSha3_384,
    #[cfg(has_rsapsssha3_512)]   RsaPssSha3_512,
    #[cfg(has_rsapsssha384)]     RsaPssSha384,
    #[cfg(has_rsapsssha512)]     RsaPssSha512,
    #[cfg(has_rsa_ripemd160)]    RsaRipemd160,
    #[cfg(has_rsa_sha1)]         RsaSha1,
    #[cfg(has_rsa_sha224)]       RsaSha224,
    #[cfg(has_rsa_sha256)]       RsaSha256,
    #[cfg(has_rsa_sha384)]       RsaSha384,
    #[cfg(has_rsa_sha512)]       RsaSha512,
    #[cfg(has_sha1)]             Sha1,
    #[cfg(has_sha224)]           Sha224,
    #[cfg(has_sha256)]           Sha256,
    #[cfg(has_sha384)]           Sha384,
    #[cfg(has_sha512)]           Sha512,
    #[cfg(has_sha3_224)]         Sha3_224,
    #[cfg(has_sha3_256)]         Sha3_256,
    #[cfg(has_sha3_384)]         Sha3_384,
    #[cfg(has_sha3_512)]         Sha3_512,
}

impl XmlSecSignatureMethod {
    /// Returns the resource pointer for the corresponding digesting/signing resource
    pub fn to_method(&self) -> bindings::xmlSecTransformId {
        match self {
            #[cfg(has_aes128_cbc)]       Self::Aes128Cbc => unsafe { bindings::xmlSecOpenSSLTransformAes128CbcGetKlass() },
            #[cfg(has_aes128_gcm)]       Self::Aes128Gcm => unsafe { bindings::xmlSecOpenSSLTransformAes128GcmGetKlass() },
            #[cfg(has_aes192_cbc)]       Self::Aes192Cbc => unsafe { bindings::xmlSecOpenSSLTransformAes192CbcGetKlass() },
            #[cfg(has_aes192_gcm)]       Self::Aes192Gcm => unsafe { bindings::xmlSecOpenSSLTransformAes192GcmGetKlass() },
            #[cfg(has_aes256_cbc)]       Self::Aes256Cbc => unsafe { bindings::xmlSecOpenSSLTransformAes256CbcGetKlass() },
            #[cfg(has_aes256_gcm)]       Self::Aes256Gcm => unsafe { bindings::xmlSecOpenSSLTransformAes256GcmGetKlass() },
            #[cfg(has_concatkdf)]        Self::ConcatKdf => unsafe { bindings::xmlSecOpenSSLTransformConcatKdfGetKlass() },
            #[cfg(has_des3_cbc)]         Self::Des3Cbc => unsafe { bindings::xmlSecOpenSSLTransformDes3CbcGetKlass() },
            #[cfg(has_dhes)]             Self::DhEs => unsafe { bindings::xmlSecOpenSSLTransformDhEsGetKlass() },
            #[cfg(has_dsa_sha1)]         Self::DsaSha1 => unsafe { bindings::xmlSecOpenSSLTransformDsaSha1GetKlass() },
            #[cfg(has_dsa_sha256)]       Self::DsaSha256 => unsafe { bindings::xmlSecOpenSSLTransformDsaSha256GetKlass() },
            #[cfg(has_ecdh)]             Self::Ecdh => unsafe { bindings::xmlSecOpenSSLTransformEcdhGetKlass() },
            #[cfg(has_ecdsa_ripemd160)]  Self::EcdsaRipemd160 => unsafe { bindings::xmlSecOpenSSLTransformEcdsaRipemd160GetKlass() },
            #[cfg(has_ecdsa_sha1)]       Self::EcdsaSha1 => unsafe { bindings::xmlSecOpenSSLTransformEcdsaSha1GetKlass() },
            #[cfg(has_ecdsa_sha224)]     Self::EcdsaSha224 => unsafe { bindings::xmlSecOpenSSLTransformEcdsaSha224GetKlass() },
            #[cfg(has_ecdsa_sha256)]     Self::EcdsaSha256 => unsafe { bindings::xmlSecOpenSSLTransformEcdsaSha256GetKlass() },
            #[cfg(has_ecdsa_sha3_224)]   Self::EcdsaSha3_224 => unsafe { bindings::xmlSecOpenSSLTransformEcdsaSha3_224GetKlass() },
            #[cfg(has_ecdsa_sha3_256)]   Self::EcdsaSha3_256 => unsafe { bindings::xmlSecOpenSSLTransformEcdsaSha3_256GetKlass() },
            #[cfg(has_ecdsa_sha3_384)]   Self::EcdsaSha3_384 => unsafe { bindings::xmlSecOpenSSLTransformEcdsaSha3_384GetKlass() },
            #[cfg(has_ecdsa_sha3_512)]   Self::EcdsaSha3_512 => unsafe { bindings::xmlSecOpenSSLTransformEcdsaSha3_512GetKlass() },
            #[cfg(has_ecdsa_sha384)]     Self::EcdsaSha384 => unsafe { bindings::xmlSecOpenSSLTransformEcdsaSha384GetKlass() },
            #[cfg(has_ecdsa_sha512)]     Self::EcdsaSha512 => unsafe { bindings::xmlSecOpenSSLTransformEcdsaSha512GetKlass() },
            #[cfg(has_gost2001)]         Self::Gost2001 => unsafe { bindings::xmlSecOpenSSLTransformGost2001GostR3411_94GetKlass() },
            #[cfg(has_gost2012_256)]     Self::Gost2012_256 => unsafe { bindings::xmlSecOpenSSLTransformGostR3410_2012GostR3411_2012_256GetKlass() },
            #[cfg(has_gost2012_512)]     Self::Gost2012_512 => unsafe { bindings::xmlSecOpenSSLTransformGostR3410_2012GostR3411_2012_512GetKlass() },
            #[cfg(has_gost94)]           Self::Gost94 => unsafe { bindings::xmlSecOpenSSLTransformGostR3411_94GetKlass() },
            #[cfg(has_hmac_md5)]         Self::HmacMd5 => unsafe { bindings::xmlSecOpenSSLTransformHmacMd5GetKlass() },
            #[cfg(has_hmac_ripemd160)]   Self::HmacRipemd160 => unsafe { bindings::xmlSecOpenSSLTransformHmacRipemd160GetKlass() },
            #[cfg(has_hmac_sha1)]        Self::HmacSha1 => unsafe { bindings::xmlSecOpenSSLTransformHmacSha1GetKlass() },
            #[cfg(has_hmac_sha224)]      Self::HmacSha224 => unsafe { bindings::xmlSecOpenSSLTransformHmacSha224GetKlass() },
            #[cfg(has_hmac_sha256)]      Self::HmacSha256 => unsafe { bindings::xmlSecOpenSSLTransformHmacSha256GetKlass() },
            #[cfg(has_hmac_sha384)]      Self::HmacSha384 => unsafe { bindings::xmlSecOpenSSLTransformHmacSha384GetKlass() },
            #[cfg(has_hmac_sha512)]      Self::HmacSha512 => unsafe { bindings::xmlSecOpenSSLTransformHmacSha512GetKlass() },
            #[cfg(has_kw_aes128)]        Self::KWAes128 => unsafe { bindings::xmlSecOpenSSLTransformKWAes128GetKlass() },
            #[cfg(has_kw_aes192)]        Self::KWAes192 => unsafe { bindings::xmlSecOpenSSLTransformKWAes192GetKlass() },
            #[cfg(has_kw_aes256)]        Self::KWAes256 => unsafe { bindings::xmlSecOpenSSLTransformKWAes256GetKlass() },
            #[cfg(has_kw_des3)]          Self::KWDes3 => unsafe { bindings::xmlSecOpenSSLTransformKWDes3GetKlass() },
            #[cfg(has_md5)]              Self::Md5 => unsafe { bindings::xmlSecOpenSSLTransformMd5GetKlass() },
            #[cfg(has_pbkdf2)]           Self::Pbkdf2 => unsafe { bindings::xmlSecOpenSSLTransformPbkdf2GetKlass() },
            #[cfg(has_ripemd160)]        Self::Ripemd160 => unsafe { bindings::xmlSecOpenSSLTransformRipemd160GetKlass() },
            #[cfg(has_rsa_md5)]          Self::RsaMd5 => unsafe { bindings::xmlSecOpenSSLTransformRsaMd5GetKlass() },
            #[cfg(has_rsaoaep_enc11)]    Self::RsaOaepEnc11 => unsafe { bindings::xmlSecOpenSSLTransformRsaOaepEnc11GetKlass() },
            #[cfg(has_rsa_oaep)]         Self::RsaOaep => unsafe { bindings::xmlSecOpenSSLTransformRsaOaepGetKlass() },
            #[cfg(has_rsa_pkcs1)]        Self::RsaPkcs1 => unsafe { bindings::xmlSecOpenSSLTransformRsaPkcs1GetKlass() },
            #[cfg(has_rsapsssha1)]       Self::RsaPssSha1 => unsafe { bindings::xmlSecOpenSSLTransformRsaPssSha1GetKlass() },
            #[cfg(has_rsapsssha224)]     Self::RsaPssSha224 => unsafe { bindings::xmlSecOpenSSLTransformRsaPssSha224GetKlass() },
            #[cfg(has_rsapsssha256)]     Self::RsaPssSha256 => unsafe { bindings::xmlSecOpenSSLTransformRsaPssSha256GetKlass() },
            #[cfg(has_rsapsssha3_224)]   Self::RsaPssSha3_224 => unsafe { bindings::xmlSecOpenSSLTransformRsaPssSha3_224GetKlass() },
            #[cfg(has_rsapsssha3_256)]   Self::RsaPssSha3_256 => unsafe { bindings::xmlSecOpenSSLTransformRsaPssSha3_256GetKlass() },
            #[cfg(has_rsapsssha3_384)]   Self::RsaPssSha3_384 => unsafe { bindings::xmlSecOpenSSLTransformRsaPssSha3_384GetKlass() },
            #[cfg(has_rsapsssha3_512)]   Self::RsaPssSha3_512 => unsafe { bindings::xmlSecOpenSSLTransformRsaPssSha3_512GetKlass() },
            #[cfg(has_rsapsssha384)]     Self::RsaPssSha384 => unsafe { bindings::xmlSecOpenSSLTransformRsaPssSha384GetKlass() },
            #[cfg(has_rsapsssha512)]     Self::RsaPssSha512 => unsafe { bindings::xmlSecOpenSSLTransformRsaPssSha512GetKlass() },
            #[cfg(has_rsa_ripemd160)]    Self::RsaRipemd160 => unsafe { bindings::xmlSecOpenSSLTransformRsaRipemd160GetKlass() },
            #[cfg(has_rsa_sha1)]         Self::RsaSha1 => unsafe { bindings::xmlSecOpenSSLTransformRsaSha1GetKlass() },
            #[cfg(has_rsa_sha224)]       Self::RsaSha224 => unsafe { bindings::xmlSecOpenSSLTransformRsaSha224GetKlass() },
            #[cfg(has_rsa_sha256)]       Self::RsaSha256 => unsafe { bindings::xmlSecOpenSSLTransformRsaSha256GetKlass() },
            #[cfg(has_rsa_sha384)]       Self::RsaSha384 => unsafe { bindings::xmlSecOpenSSLTransformRsaSha384GetKlass() },
            #[cfg(has_rsa_sha512)]       Self::RsaSha512 => unsafe { bindings::xmlSecOpenSSLTransformRsaSha512GetKlass() },
            #[cfg(has_sha1)]             Self::Sha1 => unsafe { bindings::xmlSecOpenSSLTransformSha1GetKlass() },
            #[cfg(has_sha224)]           Self::Sha224 => unsafe { bindings::xmlSecOpenSSLTransformSha224GetKlass() },
            #[cfg(has_sha256)]           Self::Sha256 => unsafe { bindings::xmlSecOpenSSLTransformSha256GetKlass() },
            #[cfg(has_sha384)]           Self::Sha384 => unsafe { bindings::xmlSecOpenSSLTransformSha384GetKlass() },
            #[cfg(has_sha512)]           Self::Sha512 => unsafe { bindings::xmlSecOpenSSLTransformSha512GetKlass() },
            #[cfg(has_sha3_224)]         Self::Sha3_224 => unsafe { bindings::xmlSecOpenSSLTransformSha3_224GetKlass() },
            #[cfg(has_sha3_256)]         Self::Sha3_256 => unsafe { bindings::xmlSecOpenSSLTransformSha3_256GetKlass() },
            #[cfg(has_sha3_384)]         Self::Sha3_384 => unsafe { bindings::xmlSecOpenSSLTransformSha3_384GetKlass() },
            #[cfg(has_sha3_512)]         Self::Sha3_512 => unsafe { bindings::xmlSecOpenSSLTransformSha3_512GetKlass() },
            _ => panic!("This signature method is not available in your xmlsec build."),
        }
    }
}